port: 6006

weaviate:
  host: "localhost"
  port: "8079"

embedding:
  device: "cuda:0"
  embedding_path: "/root/autodl-tmp/llm/BAAI/bge-large-zh-v1.5"


vllm:
  model: "/root/autodl-tmp/llm/Qwen2-72B-Instruct-GPTQ-Int4"
  tensor_parallel_size: 4
  quantization: "gptq"
  seed: 42

mysql:
  xxlxdb:
    host: "120.92.116.101"
    port: 9200
    user: "read"
    password: "Xxedu_only_Read123!@#"
    database: "xxlxdb"
  smart_counselor:
    host: "120.92.116.101"
    port: 9200
    user: "read"
    password: "Xxedu_only_Read123!@#"
    database: "smart_counselor"

redis:
  host: "192.168.0.188"
  port: 6379
  db: 12
  password: "aoji123!@#"
  max_retries: 5
  retry_delay: 3


