port: 8000

weaviate:
  #  host: "192.168.0.139"
  #  port: "8080"
  #  grpc_port: "50051"
  host: "127.0.0.1"
  port: "8079"
  grpc_port: "50060"

embedding:
  device: "cpu"
  embedding_path: "D:/LLM/BAAI/bge-large-zh-v1.5"

vllm:
  model: "/root/autodl-tmp/llm/Qwen2-72B-Instruct-GPTQ-Int4"
  tensor_parallel_size: 4
  quantization: "gptq"
  seed: 42

mysql:
  xxlxdb:
    host: "192.168.0.137"
    port: 3306
    user: "root"
    password: "mirandA123!@#"
    database: "test_xxlxdb"
  smart_counselor:
    host: "192.168.0.137"
    port: 3306
    user: "root"
    password: "mirandA123!@#"
    database: "test_smart_counselor"
#120.92.38.14
#58818
redis:
  host: "59.108.41.117"
  port: 26379
  db: 12
  password: "aoji123!@#"
  max_retries: 5
  retry_delay: 3


google_search: "http://127.0.0.1:5000/search?query="
search_text: "http://127.0.0.1:5000/search_text?url="
